# Generated by Django 3.0.3 on 2020-03-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='movie',
            new_name='film',
        ),
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(related_name='filmmaker', to='movies.Filmmaker', verbose_name='режиссер'),
        ),
    ]
