# Generated by Django 3.0.3 on 2020-03-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200313_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='directors',
            new_name='filmmaker',
        ),
    ]
