# Generated by Django 3.0.3 on 2020-03-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200313_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='filmmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmmaker', to='movies.Filmmaker', verbose_name='режиссер'),
        ),
    ]
