# Generated by Django 3.0.3 on 2020-03-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200313_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
