# Generated by Django 3.0.3 on 2020-03-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
