# Generated by Django 3.0.3 on 2020-03-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200315_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmaker',
            name='url',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
