# Generated by Django 3.0.3 on 2020-03-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
