# Generated by Django 3.0.3 on 2020-03-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
